<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Mvc" Version="10.0.0" />
        <PackageReference Include="AutoMapper" Version="16.1.1" />
        <PackageReference Include="FluentValidation" Version="12.1.1" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TaskTracker.Application\TaskTracker.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
        <!-- Remove Generator and LastGenOutput to stop auto-generation -->
        <EmbeddedResource Update="Resources\GlobalResources.resx">
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <!-- Remove the compile update block for the designer file -->
        <Compile Remove="Properties\Resources.Designer.cs" />
    </ItemGroup>
</Project>
